### PR TITLE
dialogue volume slider and automatic volume adjustment on load

### PR DESCRIPTION
**Pull request by ronanhub**
-volume automatically gets set to the right level when starting the game
-added dialogue volume slider: changes Dialogue volume in audiomixer

### CODE REVIEW

**Comment by ronanhub** [comment]
lower keycard sound a little (lower keycard sound a little)

- lower keycard sound a little
- lower keycard sound a little (lower keycard sound a little)
    - lower keycard sound a little

**Comment by ronanhub** [comment]
closed voor meer changes

**Comment by ronanhub** [comment]
footsteps now alert guards

**Review by Jarivanoort — APPROVED** [review]
alles workey

**Review by MatthijsHofele — CHANGES_REQUESTED** [review]
Kan dit ook voor het titlescreen? Voor de rest is alles goed

**Pull request merged**
